destroy-network/action.yml, init-testnet-deploy/action.yml, launch-network/action.yml, network-status/action.yml, print-inventory/action.yml, start-nodes/action.yml, stop-telegraf/action.yml, upgrade-network/action.yml, upgrade-node-man/action.yml, upgrade-telegraf-config/action.yml, upscale-network/action.yml
We can arrange multiple actions within one repository. In this initial commit, several are merged from different repositories:
* Initialise the testnet-deploy tool
* Launch a network
* Destroy a network
* Upscale a network
* Upgrade Telegraf configuration
* Upgrade node manager
* Upgrade network
* Stop Telegraf
* Start nodes
* Print inventory
* Network status
=> feat: provide actions from smaller repositories

start-telegraf/action.yml, stop-telegraf/action.yml
- db87609 **feat: custom inventory input for stopping telegraf**
Enables the playbook to run against select VMs.
- f262eca **feat: provide start telegraf workflow**
This can be useful for upgrades.
There is another workflow for upgrading the Telegraf configuration, which will also start the
service, but it's not always appropriate to update the configuration. This workflow can be used to
start the service without also upgrading the configuration.
=> feat: provide start telegraf workflow

upgrade-node-man/action.yml
This will also be part of the upgrade process for the next release.
We should only upgrade one machine and make sure that's OK.
=> feat: custom inventory input for upgrade node manager

infra-plan/action.yml, upscale-network/action.yml
- 39f0a77 **feat: provide an infra-plan action**
Uses `testnet-deploy` to run `terraform plan` against an existing environment.
Useful testing the impact of changes on the production environment.
- 36aecd1 **feat: new auditor inputs for upscaling action**
Also provides the ability to only run Terraform, and only run a plan rather than an apply.
=> feat: new auditor inputs for upscaling action

start-faucet/action.yml, stop-faucet/action.yml
These will use new `testnet-deploy` commands for starting and stopping the faucet.
=> feat: provide actions for controlling the faucet

upgrade-node-telegraf-config/action.yml, upgrade-uploader-telegraf-config/action.yml
- 294835c **refactor: rename `upgrade-telegraf-config` action**
We are going to introduce a new action, specifically for upgrading the uploader configuration, so we
need to rename this one to be less generic.
- 8287b06 **feat: provide `upgrade-uploader-telegraf-config` action**
This will use a new `testnet-deploy` command to upload the Telegraf config for the uploaders.
=> feat: provide `upgrade-uploader-telegraf-config` action

bootstrap-network/action.yml
Uses the new `bootstrap` command on `testnet-deploy` to launch a new network that uses a peer to bootstrap from an existing network.
=> feat: provide `bootstrap-network` action

upgrade-uploaders/action.yml
Use `testnet-deploy` to upgrade the version of `safe` on the uploaders.
=> feat: provide `upgrade-uploaders` action

launch-network/action.yml
This argument is now supported by `testnet-tool` for varying the chunk size when using a custom build.
=> feat: provide `chunk-size` input

upscale-network/action.yml
This input must be used when upscaling the uploaders, to put the correct version of `safe` on the machines.
=> feat: provide `safe-version` input

configure-swapfile/action.yml
Uses the new `testnet-deploy` command to setup a swapfile on node VMs, and optionally on the bootstrap VMs.
=> feat: provide `configure-swapfile` action

launch-network/action.yml, upscale-network/action.yml
Allows us to pass a value for the `--desired-uploaders-count` argument on the `upscale` command and the `uploaders-count` argument on the `deploy` command.
=> feat: provide `uploaders-count` inputs

upscale-uploaders/action.yml
Using this flag will cause `testnet-deploy` to only run the Ansible provision and not Terraform.
=> feat: provide `provision-only` input

start-nodes/action.yml, upgrade-network/action.yml, upgrade-uploaders/action.yml
- 1028447 **chore: remove faucet and auditor inputs**
These components are no longer part of the network.
- af6e927 **chore: rename `safenode-version` input to `version`**
Now that the faucet doesn't exist, there is no need to qualify the version.
- 57bbe7d **fix: use the `--version` argument**
The `Upgrade Uploaders` workflow was not actually applying this argument.
- 51c1a83 **feat: provide `interval` arg**
The `start` command now supports this.
=> More Changes to Support EVM-based Networks

bootstrap-network/action.yml, launch-network/action.yml, upscale-network/action.yml
- 8c25197 **feat: provide `interval` inputs on various actions**
The `testnet-deploy` tool now supports an interval on these commands.
- 4bf3c58 **fix: only use non-zero counts**
The counts should not be used if they are set to 0.
Downscaling would not be a legitimate operation anyway.
=> feat: provide `interval` inputs on various actions

upgrade-network/action.yml
This can be useful for an upgrade where there is one node per machine, such as bootstrap nodes.
=> feat: provide `delay` input to upgrade action

upscale-network/action.yml
These two arguments can be used to provide a newer version on the upscale. This would prevent having to upgrade as an additional step.
=> feat: provide version inputs for upscale

stop-nodes/action.yml
The `testnet-deploy stop` command now supports a `--delay` argument, which is useful for stopping a set of nodes when there is only one node running on each machine.
=> feat: provide `delay` input

update-peer/action.yml
Uses the `testnet-deploy update-peer` command, which in turn updates each safenode service definition to use a new peer to connect to.
=> feat: provide `update-peer` action

kill-droplets/action.yml
This can be used to delete individual droplets without deleting a whole environment.
This can sometimes be necessary.
=> feat: provide `kill-droplets` action

launch-network/action.yml
This allows us to run a staging comparison using different contract addresses.
=> feat: provide evm contract address inputs

launch-network/action.yml
It is now valid to pass the funding wallet secret key for a custom network.
=> chore: remove condition on custom network type

bootstrap-network/action.yml, launch-network/action.yml, upgrade-antctl/action.yml, upgrade-network/action.yml, upscale-network/action.yml
- b88c28f **chore: rename `launch-network` inputs for autonomi branding**
We recently renamed our our binaries and crates and this has had other cascading effects on tools
like `testnet-deploy`.
- 757a16d **chore: align inputs with new peer cache infra**
Several changes here:
* `bootstrap-`-related inputs have been changed to `peer-cache`.
* Inputs for volume sizes have been added.
* The key-based inputs have been removed, since these are no longer used any more.
* A `network-id` input has been added.
- dcb3d75 **chore: rename `upscale` version inputs**
This brings them in alignment with the rebranding.
- 3ca1dfc **chore: rename `upgrade-node-man` action to `upgrade-antctl`**
- 9b6272c **chore: provide `force` input for `upgrade-network`**
- ef838f3 **chore: rebrand the …
=> Various Changes to Support Rebranding

upscale-network/action.yml
The `testnet-deploy upscale` command now supports using a custom branch reference.
=> chore: inputs for custom branch

upscale-network/action.yml
- fc65584 **chore: align arguments with inputs**
The inputs for the upscale action were not aligned with the arguments for the `upscale` command.
- 63d3a50 **chore: add `funding-wallet-secret-key` input**
- 7260bfa **fix: use correct input references**
=> chore: align arguments with inputs

init-testnet-deploy/action.yml
I need to obtain the version of the Digital Ocean provider that is being used with the runs on GHA.
=> chore: print terraform version during setup

launch-network/action.yml
This was now changed in `testnet-deploy` to use `autonomi` rather than `safe`.
=> chore: update inventory path

start-nodes/action.yml, stop-nodes/action.yml
This facilitates stopping individual services rather than every service.
The same input is also added to the `start` action, though `testnet-deploy` doesn't support that yet. I'm just adding it because it's quite probable that at some point we will have support for it.
=> feat: support service name args on `stop` action

launch-network/action.yml, provision/action.yml
- fb15553 **feat: provide `to-genesis` input**
If set to true, the deploy will only run until the point of provisioning the genesis node.
Other steps can then run in parallel.
- 9e75e4a **feat: provide `provision` action**
This will run the provisioning command, which can be used for deploys that run the provisions in
parallel.
=> Support Parallel Deployments

launch-network/action.yml
Uses a new argument on `testnet-deploy` for disabling Telegraf in a deployment.
=> feat: provide `disable-telegraf` input

launch-network/action.yml
This new argument for `testnet-deploy` enables setting environment variables for the `ant` binary.
The generic `environment-vars` input was renamed to `node-env` to be more specific.
The names of these inputs now correspond to the names of the arguments on the command.
=> feat: provide `client-env` input

bootstrap-network/action.yml
This is required for the bootstrap network to be able to connect to the original.
If we want to connect to the `mainnet`, we can just explicitly use `1` as the value. This is better than making it optional, because we will inevitably forget to provide it, and most of the time we won't be bootstrapping from `mainnet`.
=> feat: provide `network-id` input

bootstrap-network/action.yml
Either the peer or the network contacts URL can be provided.
=> chore: make `peer` input optional

bootstrap-network/action.yml, launch-network/action.yml
The `testnet-deploy` tool now supports a `--region` argument for deploy-related commands, so the `launch-network` and `bootstrap-network` actions are updated to expose an input for it.
=> feat: provide `region` input

telegraf-upgrade-client-config/action.yml, telegraf-upgrade-geoip-config/action.yml, telegraf-upgrade-node-config/action.yml
- 3e33948 **chore: use `telegraf` subcommand**
The `testnet-deploy` binary was updated to group these commands under a `telegraf` subcommand, so
these actions are subsequently updated.
The roles are also renamed to align them closer to the name of the subcommand and also group them
together.
- 1af59e6 **feat: provide `telegraf-upgrade-geoip-config` action**
Provide action to run the new `telegraf upgrade-geoip-config` command in `testnet-deploy`.
=> feat: provide `telegraf-upgrade-geoip-config` action

client-deploy/action.yml
This wraps around the new `clients deploy` command and will be used mainly for running performance tests against the production network.
=> feat: provide `client-deploy` action

client-deploy/action.yml
There are two different inputs related to the funding wallets now. You can either supply the secret of a wallet that will fund other wallets that get created during the deploy process, or you can supply secret keys for pre-funded wallets. The latter is useful for working with the production network, just so you can have more control over the management of the funds.
=> chore: provide `funding-wallet-secret-key` input

init-testnet-deploy/action.yml
Since the client run uses a separate Terraform manifest, it uses a different variable for the state file.
=> chore: provide new variable for terraform state

upscale-network/action.yml
We need to support this argument on upscaling so that all nodes on a network would run with verbose logging.
=> feat: provide `node-env` input

client-deploy/action.yml
The `testnet-deploy` tool now supports an `--upload-size` argument that enables varying file sizes for continuous uploads.
=> feat: provide `upload-size` input

init-testnet-deploy/action.yml
For some reason there is now a failure when trying to check out a particular version of testnet-deploy.
Adding some debugging text just to confirm if we are getting rate-limited or something when we try to get the latest version from `crates.io`.
=> chore: debugging output to print version

init-testnet-deploy/action.yml
- 8a3c08d **chore: check the version returned by crates.io**
It seems the case that the request to retrieve the latest version from crates.io possibly gets rate
limited when the request is made from Github. If I run the same request from my dev machine, it is
fine, but when run from Github it is returning the string "null".
If the version hasn't been retrieved correctly, we can just use the latest code rather than check
out a specific version.
- e416602 **chore: use git repo to retrieve latest version**
Trying to use `crates.io` seems to be temperamental.
Get the latest version using the latest tag in the repository.
=> chore: use git repo to retrieve latest version

init-testnet-deploy/action.yml, launch-network/action.yml
- d9d60d4 **chore: remove ansible version constraint**
We can now run on the latest version of Ansible.
- 9f9b993 **chore: rename full cone vm size inputs/args**
This argument was recently renamed with a rework of the full cone private node setup.
=> chore: rename full cone vm size inputs/args
